AWSTemplateFormatVersion: "2010-09-09"
Description: >
  API stack for aws-ecommerce-infrastructure.
  Creates HTTP API Gateway with Lambda integration for /api/* routes.



Parameters:

  ProjectName:
    Type: String

  Environment:
    Type: String

  LambdaS3Bucket:
    Type: String

  ProductsLambdaS3Key:
    Type: String

  CartLambdaS3Key:
    Type: String

  CheckoutLambdaS3Key:
    Type: String

  OrdersLambdaS3Key:
    Type: String



Resources:
