AWSTemplateFormatVersion: "2010-09-09"
Description: >
  API stack for aws-ecommerce-infrastructure.
  Creates HTTP API Gateway with routes, authorizers, and Lambda integrations.



Parameters:

  ProjectName:
    Type: String

  Environment:
    Type: String
  
  DomainName:
    Type: String

  ThrottleBurstLimit:
    Type: Number

  ThrottleRateLimit:
    Type: Number



Conditions:

  IsProd: !Equals [!Ref Environment, prod]



Resources:

  # ----------------------
  # HTTP API
  # ----------------------

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-api"
      Description: !Sub "Ecommerce API for ${ProjectName}-${Environment}"
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - !If
            - IsProd
            - !Sub "https://${DomainName}"
            - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Amz-Date
          - X-Api-Key
          - X-Amz-Security-Token
        MaxAge: 3600
        AllowCredentials: true
      Tags:
        Project: !Ref ProjectName
        Environment: !Ref Environment


  # ----------------------
  # JWT Authorizer
  # ----------------------

  JwtAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-jwt-authorizer"
      ApiId: !Ref HttpApi
      AuthorizerType: JWT
      IdentitySource:
        - $request.header.Authorization
      JwtConfiguration:
        Audience:
          - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-CognitoUserPool"
        Issuer:
          Fn::ImportValue: !Sub "${ProjectName}-${Environment}-CognitoDomain"


  # ----------------------
  # Api Integrations
  # ----------------------
  
  CartAddIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations"
        - FunctionArn:
            Fn::ImportValue: !Sub "${ProjectName}-${Environment}-CartAddFunctionArn"
      IntegrationMethod: POST
      PayloadFormatVersion: "2.0"
      TimeoutInMillis: 30000

  CartGetIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations"
        - FunctionArn:
            Fn::ImportValue: !Sub "${ProjectName}-${Environment}-CartGetFunctionArn"
      IntegrationMethod: GET
      PayloadFormatVersion: "2.0"
      TimeoutInMillis: 30000

  CartUpdateIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations"
        - FunctionArn:
            Fn::ImportValue: !Sub "${ProjectName}-${Environment}-CartUpdateFunctionArn"
      IntegrationMethod: PUT
      PayloadFormatVersion: "2.0"
      TimeoutInMillis: 30000

  CartRemoveIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations"
        - FunctionArn:
            Fn::ImportValue: !Sub "${ProjectName}-${Environment}-CartRemoveFunctionArn"
      IntegrationMethod: DELETE
      PayloadFormatVersion: "2.0"
      TimeoutInMillis: 30000

  CartClearIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations"
        - FunctionArn:
            Fn::ImportValue: !Sub "${ProjectName}-${Environment}-CartClearFunctionArn"
      IntegrationMethod: DELETE
      PayloadFormatVersion: "2.0"
      TimeoutInMillis: 30000

  ProductsGetIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations"
        - FunctionArn:
            Fn::ImportValue: !Sub "${ProjectName}-${Environment}-ProductsGetFunctionArn"
      IntegrationMethod: GET
      PayloadFormatVersion: "2.0"
      TimeoutInMillis: 30000

  CheckoutIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations"
        - FunctionArn:
            Fn::ImportValue: !Sub "${ProjectName}-${Environment}-CheckoutFunctionArn"
      IntegrationMethod: POST
      PayloadFormatVersion: "2.0"
      TimeoutInMillis: 60000

  ProfileGetIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations"
        - FunctionArn:
            Fn::ImportValue: !Sub "${ProjectName}-${Environment}-ProfileGetFunctionArn"
      IntegrationMethod: GET
      PayloadFormatVersion: "2.0"
      TimeoutInMillis: 30000

  OrdersGetIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations"
        - FunctionArn:
            Fn::ImportValue: !Sub "${ProjectName}-${Environment}-OrdersGetFunctionArn"
      IntegrationMethod: GET
      PayloadFormatVersion: "2.0"
      TimeoutInMillis: 30000

  NotFoundIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations"
        - FunctionArn:
            Fn::ImportValue: !Sub "${ProjectName}-${Environment}-NotFoundFunctionArn"
      IntegrationMethod: POST
      PayloadFormatVersion: "2.0"
      TimeoutInMillis: 30000


  # ----------------------
  # Routes
  # ----------------------

  CartAddGuestRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: POST /api/cart/items/{productId}
      Target: !Sub "integrations/${CartAddIntegration}"

  CartAddAuthRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: POST /api/cart/items/{productId}/auth
      Target: !Sub "integrations/${CartAddIntegration}"
      AuthorizationType: JWT
      AuthorizerId: !Ref JwtAuthorizer

  CartGetGuestRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: GET /api/cart
      Target: !Sub "integrations/${CartGetIntegration}"

  CartGetAuthRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: GET /api/cart/auth
      Target: !Sub "integrations/${CartGetIntegration}"
      AuthorizationType: JWT
      AuthorizerId: !Ref JwtAuthorizer

  CartUpdateGuestRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: PUT /api/cart/items/{productId}
      Target: !Sub "integrations/${CartUpdateIntegration}"

  CartUpdateAuthRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: PUT /api/cart/items/{productId}/auth
      Target: !Sub "integrations/${CartUpdateIntegration}"
      AuthorizationType: JWT
      AuthorizerId: !Ref JwtAuthorizer

  CartRemoveGuestRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: DELETE /api/cart/items/{productId}
      Target: !Sub "integrations/${CartRemoveIntegration}"

  CartRemoveAuthRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: DELETE /api/cart/items/{productId}/auth
      Target: !Sub "integrations/${CartRemoveIntegration}"
      AuthorizationType: JWT
      AuthorizerId: !Ref JwtAuthorizer

  CartClearGuestRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: DELETE /api/cart
      Target: !Sub "integrations/${CartClearIntegration}"

  CartClearAuthRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: DELETE /api/cart/auth
      Target: !Sub "integrations/${CartClearIntegration}"
      AuthorizationType: JWT
      AuthorizerId: !Ref JwtAuthorizer

  ProductsGetRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: GET /api/products
      Target: !Sub "integrations/${ProductsGetIntegration}"

  CheckoutRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: POST /api/checkout/auth
      Target: !Sub "integrations/${CheckoutIntegration}"
      AuthorizationType: JWT
      AuthorizerId: !Ref JwtAuthorizer

  ProfileGetRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: GET /api/user/profile/auth
      Target: !Sub "integrations/${ProfileGetIntegration}"
      AuthorizationType: JWT
      AuthorizerId: !Ref JwtAuthorizer

  OrdersGetRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: GET /api/orders/auth
      Target: !Sub "integrations/${OrdersGetIntegration}"
      AuthorizationType: JWT
      AuthorizerId: !Ref JwtAuthorizer

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: $default
      Target: !Sub "integrations/${NotFoundIntegration}"


  # ----------------------
  # Stage & Deployment
  # ----------------------

  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: !Ref Environment
      ApiId: !Ref HttpApi
      AutoDeploy: true
      Description: !Sub "${Environment} stage"
      AccessLogSettings:
        DestinationArn: !GetAtt ApiLogGroup.Arn
        Format: >-
          {"requestId":"$context.requestId",
          "ip":"$context.identity.sourceIp",
          "requestTime":"$context.requestTime",
          "httpMethod":"$context.httpMethod",
          "routeKey":"$context.routeKey",
          "status":"$context.status",
          "protocol":"$context.protocol",
          "responseLength":"$context.responseLength",
          "integrationError":"$context.integrationErrorMessage",
          "userAgent":"$context.identity.userAgent",
          "authorizer":"$context.authorizer.claims.sub"}
      DefaultRouteSettings:
        ThrottlingBurstLimit: !Ref ThrottleBurstLimit
        ThrottlingRateLimit: !Ref ThrottleRateLimit
        DetailedMetricsEnabled: !If [IsProd, true, false]
      Tags:
        Project: !Ref ProjectName
        Environment: !Ref Environment

  ApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/${ProjectName}-${Environment}"
      RetentionInDays: !If [IsProd, 30, 7]
    DeletionPolicy: !If [IsProd, Retain, Delete]
    UpdateReplacePolicy: !If [IsProd, Retain, Delete]


  # ----------------------
  # Lambda Permissions
  # ----------------------

  CartAddFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue
        Fn::Sub: "${ProjectName}-${Environment}-CartAddFunctionName"
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/${Environment}/*"

  CartGetFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue
        Fn::Sub: "${ProjectName}-${Environment}-CartGetFunctionName"
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/${Environment}/*"

  CartUpdateFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue
        Fn::Sub: "${ProjectName}-${Environment}-CartUpdateFunctionName"
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/${Environment}/*"

  CartRemoveFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue
        Fn::Sub: "${ProjectName}-${Environment}-CartRemoveFunctionName"
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/${Environment}/*"

  CartClearFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue
        Fn::Sub: "${ProjectName}-${Environment}-CartClearFunctionName"
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/${Environment}/*"

  ProductsGetFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue
        Fn::Sub: "${ProjectName}-${Environment}-ProductsGetFunctionName"
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/${Environment}/*"

  CheckoutFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue
        Fn::Sub: "${ProjectName}-${Environment}-CheckoutFunctionName"
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/${Environment}/*"

  ProfileGetFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue
        Fn::Sub: "${ProjectName}-${Environment}-ProfileGetFunctionName"
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/${Environment}/*"

  OrdersGetFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue
        Fn::Sub: "${ProjectName}-${Environment}-OrdersGetFunctionName"
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/${Environment}/*"

  NotFoundFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue
        Fn::Sub: "${ProjectName}-${Environment}-NotFoundFunctionName"
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/${Environment}/*"



Outputs:

  HttpApiId:
    Description: HTTP API ID
    Value: !Ref HttpApi
    Export:
      Name: !Sub "${ProjectName}-${Environment}-HttpApiId"

  HttpApiEndpoint:
    Description: HTTP API endpoint URL
    Value: !GetAtt HttpApi.ApiEndpoint
    Export:
      Name: !Sub "${ProjectName}-${Environment}-HttpApiEndpoint"

  ApiGatewayDomainName:
    Description: API Gateway domain name (for CloudFront origin)
    Value: !Select [2, !Split ["/", !GetAtt HttpApi.ApiEndpoint]]
    Export:
      Name: !Sub "${ProjectName}-${Environment}-ApiGatewayDomainName"

  ApiStageUrl:
    Description: Full API stage URL
    Value: !Sub "${HttpApi.ApiEndpoint}/${Environment}"
    Export:
      Name: !Sub "${ProjectName}-${Environment}-ApiStageUrl"
