AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Compute stack for aws-ecommerce-infrastructure.
  Creates ECS Cluster, Fargate Task Definitions & Services, ALB, IAM roles, and connections to Aurora.


Parameters:

  ProjectName:
    Type: String
    Description: Project name prefix for resource naming
    Default: candy-store  # Delete Default
  
  Environment:
    Type: String
    Description: Deployment environment
    Default: dev  # Delete Default
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID from network stack
  
  PublicAlbSubnet1a:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet for ALB and NAT Gateway in AvailabilityZone-A (main)

  PublicAlbSubnet1b:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet for ALB in AvailabilityZone-B (backup)

  PrivateEcsSubnet2a:
    Type: AWS::EC2::Subnet::Id
    Description: Private subnet for ECS in AvailabilityZone-A (main)

  PublicEcsSubnet2b:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet for ECS in AvailabilityZone-B (backup)

  DesiredCount:
    Type: Number
    Description: Desired count for main ECS service.
    Default: 1  # Delete Default

  BackupDesiredCount:
    Type: Number
    Description: Desired count for pilot light ECS service. Can be updated by Step Functions or manually.
    Default: 0  # Delete Default
  
  EcsLogRetention:
    Type: Number
    Description: How many days to keep logs from ECS tasks
    Default: 30  # Delete Default
  
  DatabaseSecretArn:
    Type: String
    Description: ARN of Secrets Manager secret for DB credentials
  
  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Database Security Group Id

  ContainerName:
    Type: String
    Description: Container name
    Default: candy-store-api  # Delete Default
  
  ContainerVersion:
    Type: String
    Description: Container image tag to deploy (e.g. latest, v1.0.0)
    Default: latest  # Delete Default

  EcrRepositoryUri:
    Type: String
    Description: URI of ECR Repository
  
  AuroraDatabaseName:
    Type: String
    Description: Aurora database name

  AuroraWriterEndpoint:
    Type: String
    Description: Aurora database writer endpoint

  DomainName:
    Type: String
    Description: Root domain for the website (e.g. example.com)
    Default: floydmoratti.website  # Delete Default

  HostedZoneId:
    Type: String
    Description: Route 53 Hosted Zone ID for website domain


Conditions:
  IsProd: !Equals [!Ref Environment, prod]


Resources:

  # ----------------------
  # ECS Cluster
  # ----------------------

  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${ProjectName}-${Environment}-ecs-cluster"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-ecs-cluster"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
  

  # ----------------------
  # IAM Role for ECS Tasks
  # ----------------------

  EcsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${ProjectName}-${Environment}-ecs-execution-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: SecretsManagerReadAccess
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref DatabaseSecretArn
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-ecs-execution-role"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  EcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
      #  - PolicyName: !Sub "${ProjectName}-${Environment}-ecs-task-policy"
      #    PolicyDocument:
      #      Version: "2012-10-17"
      #      Statement:
      #        - Sid: Unnamed
      #          Effect: Allow
      #          Action:
      #            - secretsmanager:GetSecretValue
      #          Resource: !Ref DatabaseSecretArn
      # ManagedPolicyArns:
      #   - arn:aws:iam::aws:policy/AmazonRDSFullAccess
      #   - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-ecs-task-role"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment


  # ----------------------
  # Security Groups
  # ----------------------

  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ALB
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-alb-sg"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  AlbFromHTTPSIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref AlbSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      CidrIp: 0.0.0.0/0
      # Ingress rule: HTTPS from Internet

  AlbFromHTTPIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref AlbSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0
      # Ingress rule: HTTP from Internet
      
  AlbToEcsEgressRule:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref AlbSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      DestinationSecurityGroupId: !Ref EcsSecurityGroup
      # Egress rule: Outbound traffic from ALB to ECS as HTTP only


  EcsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS tasks
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-ecs-sg"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
  
  EcsFromAlbIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref EcsSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      SourceSecurityGroupId: !Ref AlbSecurityGroup
      # Ingress rule: HTTP from ALB to ECS only
  
  EcsToNetEgressRule:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref EcsSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      CidrIp: 0.0.0.0/0
      # Egress rule: Outbound traffic from ECS to Internet as HTTPS only
  
  EcsToDbEgressRule:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref EcsSecurityGroup
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      DestinationSecurityGroupId: !Ref DbSecurityGroup
      # Egress rule: Outbound traffic from ECS to Database on Port 5432 only
  

  DbFromEcsIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DbSecurityGroup
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref EcsSecurityGroup
      # Ingress rule: Port 5432 from ECS to Database only


  # ----------------------
  # ACM Certificate (for ALB)
  # ----------------------

  ApiAcmCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName:
        Fn::If:
          - IsProd
          - !Sub "api.${DomainName}"
          - !Sub "api.${Environment}.${DomainName}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName:
            Fn::If:
              - IsProd
              - !Sub "api.${DomainName}"
              - !Sub "api.${Environment}.${DomainName}"
          HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-alb-api-cert"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
      

  # ----------------------
  # Application Load Balancer
  # ----------------------

  Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-alb"
      Scheme: internet-facing
      Subnets:
        - !Ref PublicAlbSubnet1a
        - !Ref PublicAlbSubnet1b
      SecurityGroups:
        - !Ref AlbSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-alb"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
  
  AlbMainTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckProtocol: HTTP
      HealthCheckPath: /health
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-main-tg"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  AlbBackupTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckProtocol: HTTP
      HealthCheckPath: /health
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-backup-tg"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  AlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref Alb
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref ApiAcmCertificate
      DefaultActions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref AlbMainTargetGroup
                Weight: 100  # Main AZ-A traffic
              - TargetGroupArn: !Ref AlbBackupTargetGroup
                Weight: 0    # Pilot light AZ-B (Step Functions will adjust)
  
  AlbHttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref Alb
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: "443"
            StatusCode: HTTP_301


  # ----------------------
  # ECS Service (Main in AZ-a)
  # ----------------------

  EcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - EcsLogGroup
    Properties:
      Family: !Sub "${ProjectName}-${Environment}-task"
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref EcsExecutionRole
      TaskRoleArn: !Ref EcsTaskRole
      ContainerDefinitions: 
        - Name: !Ref ContainerName
          Essential: true
          Image: !Sub "${EcrRepositoryUri}:${ContainerVersion}"
          Cpu: "256"
          Memory: "512"
          PortMappings:
            - ContainerPort: 80
          Environment:
            - Name: DATABASE_HOST
              Value: !Ref AuroraWriterEndpoint
            - Name: DATABASE_NAME
              Value: !Ref AuroraDatabaseName
            - Name: DATABASE_PORT
              Value: "5432"
          Secrets:
            - Name: DATABASE_USERNAME
              ValueFrom: !Sub "${DatabaseSecretArn}:username"
            - Name: DATABASE_PASSWORD
              ValueFrom: !Sub "${DatabaseSecretArn}:password"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub "/ecs/${ProjectName}-${Environment}"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-ecs-task-def"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  EcsServiceMain:
    Type: AWS::ECS::Service
    DependsOn:
      - AlbListener
    Properties:
      ServiceName: !Sub "${ProjectName}-${Environment}-ecs-main"
      PlatformVersion: LATEST
      Cluster: !Ref EcsCluster
      LaunchType: FARGATE
      DeploymentController:
        Type: ECS
      TaskDefinition: !Ref EcsTaskDefinition
      DesiredCount: !Ref DesiredCount
      DeploymentConfiguration:
        MinimumHealthyPercent: 50
        MaximumPercent: 200
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      HealthCheckGracePeriodSeconds: 30
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !Ref PrivateEcsSubnet2a
          SecurityGroups:
            - !Ref EcsSecurityGroup
      LoadBalancers:
        - TargetGroupArn: !Ref AlbMainTargetGroup
          ContainerName: !Ref ContainerName
          ContainerPort: 80
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-ecs-main"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  EcsServiceBackup:
    Type: AWS::ECS::Service
    DependsOn:
      - AlbListener
    Properties:
      ServiceName: !Sub "${ProjectName}-${Environment}-ecs-backup"
      PlatformVersion: LATEST
      Cluster: !Ref EcsCluster
      LaunchType: FARGATE
      DeploymentController:
        Type: ECS
      TaskDefinition: !Ref EcsTaskDefinition
      DesiredCount: !Ref BackupDesiredCount  # pilot light service
      DeploymentConfiguration:
        MinimumHealthyPercent: 50
        MaximumPercent: 200
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      HealthCheckGracePeriodSeconds: 30
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicEcsSubnet2b
          SecurityGroups:
            - !Ref EcsSecurityGroup
      LoadBalancers:
        - TargetGroupArn: !Ref AlbBackupTargetGroup
          ContainerName: !Ref ContainerName
          ContainerPort: 80
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-ecs-backup"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment


  # ----------------------
  # Log Group
  # ----------------------

  EcsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${ProjectName}-${Environment}"
      RetentionInDays: !Ref EcsLogRetention
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-log-group"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    # Uses AWS-managed KMS key for CloudWatch Logs encryption


Outputs:
  AlbDnsName:
    Value: !GetAtt Alb.DNSName
    Description: DNS name of the Application Load Balancer
  
  AlbMainTargetGroupArn:
    Value: !GetAtt AlbMainTargetGroup.TargetGroupArn
    Description: ARN of main ALB target group in Availability Zone A (main)
  
  AlbBackupTargetGroupArn:
    Value: !GetAtt AlbBackupTargetGroup.TargetGroupArn
    Description: ARN of backup ALB target group in Availability Zone B (pilot light / failover)

  AlbHostedZoneId:
    Value: !GetAtt Alb.CanonicalHostedZoneID
    Description: Canonical hosted zone ID of the ALB