AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Compute stack for aws-ecommerce-infrastructure.
  Creates Lambda functions for Products, Cart, Checkout, and Orders APIs
  with IAM roles, logging, and environment configuration.



Parameters:

  ProjectName:
    Type: String

  Environment:
    Type: String

  LambdaCodeBucket:
    Type: String

  LambdaCodeKey:
    Type: String



Conditions:

  IsProd: !Equals [!Ref Environment, prod]



Resources:

  # ----------------------
  # IAM Roles
  # ----------------------

  ProductsLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${Environment}-products-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub "${ProjectName}-${Environment}-products-lambda-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: DynamoDbProductsTableAccess
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  # - dynamodb:PutItem
                  # - dynamodb:UpdateItem
                  # - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-ProductsTableArn"
                  - !Sub  # Include Indexes
                    - "${TableArn}/index/*"
                    - TableArn:
                        Fn::ImportValue: !Sub "${ProjectName}-${Environment}-ProductsTableArn"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  CartLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${Environment}-cart-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub "${ProjectName}-${Environment}-cart-lambda-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: DynamoDbCartsTableAccess
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:ConditionCheckItem
                Resource:
                  - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-CartsTableArn"
                  - !Sub  # Include Indexes
                    - "${TableArn}/index/*"
                    - TableArn:
                        Fn::ImportValue: !Sub "${ProjectName}-${Environment}-CartsTableArn"
              - Sid: DynamoDbProductsTableAccess
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                Resource:
                  - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-ProductsTableArn"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  CheckoutLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${Environment}-checkout-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub "${ProjectName}-${Environment}-checkout-lambda-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: DynamoDbCartsTableAccess
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:DeleteItem
                Resource:
                  - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-CartsTableArn"
              - Sid: DynamoDbOrdersTableAccess
                Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:ConditionCheckItem
                Resource:
                  - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-OrdersTableArn"
              - Sid: DynamoDbProductsTableAccess
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                Resource:
                  - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-ProductsTableArn"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  OrdersLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${Environment}-orders-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub "${ProjectName}-${Environment}-orders-lambda-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: DynamoDbOrdersTableAccess
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:ConditionCheckItem
                Resource:
                  - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-OrdersTableArn"
                  - !Sub  # Include Indexes
                    - "${TableArn}/index/*"
                    - TableArn:
                        Fn::ImportValue: !Sub "${ProjectName}-${Environment}-OrdersTableArn"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment


  # ----------------------
  # Lambda Functions
  # ----------------------

  ProductsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-products-function"
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt ProductsLambdaRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub "${LambdaCodeKey}/products.zip"
      Environment:
        Variables:
          PRODUCTS_TABLE: !ImportValue
            Fn::Sub: "${ProjectName}-${Environment}-ProductsTableName"
          ENVIRONMENT: !Ref Environment
          LOG_LEVEL: !If [IsProd, INFO, DEBUG]
      Timeout: 30
      MemorySize: 256
      ReservedConcurrentExecutions: !If [IsProd, 100, 10]
      Architectures:
        - arm64  # Graviton2
      TracingConfig:
        Mode: Active
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-products-function"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  CartFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-cart-function"
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt CartLambdaRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub "${LambdaCodeKey}/cart.zip"
      Environment:
        Variables:
          CARTS_TABLE: !ImportValue
            Fn::Sub: "${ProjectName}-${Environment}-CartsTableName"
          PRODUCTS_TABLE: !ImportValue
            Fn::Sub: "${ProjectName}-${Environment}-ProductsTableName"
          ENVIRONMENT: !Ref Environment
          LOG_LEVEL: !If [IsProd, INFO, DEBUG]
          CART_TTL_DAYS: "30"
      Timeout: 30
      MemorySize: 256
      ReservedConcurrentExecutions: !If [IsProd, 100, 10]
      Architectures:
        - arm64  # Graviton2
      TracingConfig:
        Mode: Active
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-cart-function"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  CheckoutFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-checkout-function"
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt CheckoutLambdaRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub "${LambdaCodeKey}/checkout.zip"
      Environment:
        Variables:
          CARTS_TABLE: !ImportValue
            Fn::Sub: "${ProjectName}-${Environment}-CartsTableName"
          ORDERS_TABLE: !ImportValue 
            Fn::Sub: "${ProjectName}-${Environment}-OrdersTableName"
          PRODUCTS_TABLE: !ImportValue
            Fn::Sub: "${ProjectName}-${Environment}-ProductsTableName"
          ENVIRONMENT: !Ref Environment
          LOG_LEVEL: !If [IsProd, INFO, DEBUG]
          PAYMENT_PROVIDER: "MOCK"
      Timeout: 60
      MemorySize: 512
      ReservedConcurrentExecutions: !If [IsProd, 50, 5]
      Architectures:
        - arm64  # Graviton2
      TracingConfig:
        Mode: Active
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-checkout-function"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  OrdersFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-orders-function"
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt OrdersLambdaRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub "${LambdaCodeKey}/orders.zip"
      Environment:
        Variables:
          ORDERS_TABLE: !ImportValue 
            Fn::Sub: "${ProjectName}-${Environment}-OrdersTableName"
          ENVIRONMENT: !Ref Environment
          LOG_LEVEL: !If [IsProd, INFO, DEBUG]
          PAYMENT_PROVIDER: "MOCK"
      Timeout: 30
      MemorySize: 256
      ReservedConcurrentExecutions: !If [IsProd, 50, 5]
      Architectures:
        - arm64  # Graviton2
      TracingConfig:
        Mode: Active
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-orders-function"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
  
  NotFoundFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-not-found-function"
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 3
      MemorySize: 128
      Code:
        ZipFile: |
          def handler(event, context):
              return {
                  "statusCode": 404,
                  "headers": {
                      "Content-Type": "application/json"
                  },
                  "body": '{"message":"Route not found"}'
              }



  # ----------------------
  # Log Groups
  # ----------------------

  ProductsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: !If [IsProd, Retain, Delete]
    UpdateReplacePolicy: !If [IsProd, Retain, Delete]
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ProductsFunction}"
      RetentionInDays: !If [IsProd, 30, 7]

  CartFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: !If [IsProd, Retain, Delete]
    UpdateReplacePolicy: !If [IsProd, Retain, Delete]
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CartFunction}"
      RetentionInDays: !If [IsProd, 30, 7]

  CheckoutFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: !If [IsProd, Retain, Delete]
    UpdateReplacePolicy: !If [IsProd, Retain, Delete]
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CheckoutFunction}"
      RetentionInDays: !If [IsProd, 30, 7]

  OrdersFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: !If [IsProd, Retain, Delete]
    UpdateReplacePolicy: !If [IsProd, Retain, Delete]
    Properties:
      LogGroupName: !Sub "/aws/lambda/${OrdersFunction}"
      RetentionInDays: !If [IsProd, 30, 7]

  NotFoundFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: !If [IsProd, Retain, Delete]
    UpdateReplacePolicy: !If [IsProd, Retain, Delete]
    Properties:
      LogGroupName: !Sub "/aws/lambda/${NotFoundFunction}"
      RetentionInDays: !If [IsProd, 30, 7]
  


Outputs:

  ProductsFunctionArn:
    Description: Products Lambda function ARN
    Value: !GetAtt ProductsFunction.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-ProductsFunctionArn"

  ProductsFunctionName:
    Description: Products Lambda function name
    Value: !Ref ProductsFunction
    Export:
      Name: !Sub "${ProjectName}-${Environment}-ProductsFunctionName"

  CartFunctionArn:
    Description: Cart Lambda function ARN
    Value: !GetAtt CartFunction.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CartFunctionArn"

  CartFunctionName:
    Description: Cart Lambda function name
    Value: !Ref CartFunction
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CartFunctionName"

  CheckoutFunctionArn:
    Description: Checkout Lambda function ARN
    Value: !GetAtt CheckoutFunction.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CheckoutFunctionArn"

  CheckoutFunctionName:
    Description: Checkout Lambda function name
    Value: !Ref CheckoutFunction
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CheckoutFunctionName"

  OrdersFunctionArn:
    Description: Orders Lambda function ARN
    Value: !GetAtt OrdersFunction.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-OrdersFunctionArn"

  OrdersFunctionName:
    Description: Orders Lambda function name
    Value: !Ref OrdersFunction
    Export:
      Name: !Sub "${ProjectName}-${Environment}-OrdersFunctionName"

  NotFoundFunctionArn:
    Description: NotFound Lambda function ARN
    Value: !GetAtt NotFoundFunction.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-NotFoundFunctionArn"

  NotFoundFunctionName:
    Description: NotFound Lambda function name
    Value: !Ref NotFoundFunction
    Export:
      Name: !Sub "${ProjectName}-${Environment}-NotFoundFunctionName"
