AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Data stack for aws-ecommerce-infrastructure.
  Creates DynamoDB tables for Products, Carts, and Orders with
  GSIs, encryption, backups, and TTL configuration.



Parameters:

  ProjectName:
    Type: String

  Environment:
    Type: String

  EnablePointInTimeRecovery:
    Type: String



Conditions:

  IsDev: !Equals [!Ref Environment, dev]
  IsProd: !Equals [!Ref Environment, prod]
  UseProvisionedThroughput: !Condition IsDev
  EnablePITR: !Or
    - !Equals [!Ref EnablePointInTimeRecovery, "true"]
    - !Condition IsProd



Resources:

  # ----------------------
  # DynamoDB Tables
  # ----------------------
  
  ProductsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub "${ProjectName}-${Environment}-products"
      BillingMode: !If [UseProvisionedThroughput, PROVISIONED, PAY_PER_REQUEST]
      ProvisionedThroughput: !If
        - UseProvisionedThroughput
        - ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        - !Ref AWS::NoValue
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES  # Output before and after state of changes
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [EnablePITR, true, false]
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-products"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  CartsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Sub "${ProjectName}-${Environment}-carts"
      BillingMode: !If [UseProvisionedThroughput, PROVISIONED, PAY_PER_REQUEST]
      ProvisionedThroughput: !If
        - UseProvisionedThroughput
        - ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        - !Ref AWS::NoValue
      AttributeDefinitions:
        - AttributeName: cartId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: cartId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserCartsIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput: !If
            - UseProvisionedThroughput
            - ReadCapacityUnits: 2
              WriteCapacityUnits: 2
            - !Ref AWS::NoValue
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [EnablePITR, true, false]
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-carts"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  OrdersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub "${ProjectName}-${Environment}-orders"
      BillingMode: !If [UseProvisionedThroughput, PROVISIONED, PAY_PER_REQUEST]
      ProvisionedThroughput: !If
        - UseProvisionedThroughput
        - ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        - !Ref AWS::NoValue
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: N
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserOrdersIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput: !If
            - UseProvisionedThroughput
            - ReadCapacityUnits: 2
              WriteCapacityUnits: 2
            - !Ref AWS::NoValue
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES  # Output before and after state of changes
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [EnablePITR, true, false]
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-orders"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
  
  UsersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub "${ProjectName}-${Environment}-users"
      BillingMode: !If [UseProvisionedThroughput, PROVISIONED, PAY_PER_REQUEST]
      ProvisionedThroughput: !If
        - UseProvisionedThroughput
        - ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        - !Ref AWS::NoValue
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput: !If
            - UseProvisionedThroughput
            - ReadCapacityUnits: 2
              WriteCapacityUnits: 2
            - !Ref AWS::NoValue
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES  # Output before and after state of changes
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [EnablePITR, true, false]
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-users"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
  

  # ----------------------
  # Auto Scaling (Dev Only)
  # ----------------------

  AutoScalingRole:
    Type: AWS::IAM::Role
    Condition: UseProvisionedThroughput
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: application-autoscaling.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/DynamoDBAutoscalingRole


  # Products Table Auto Scaling
  ProductsTableWriteScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: UseProvisionedThroughput
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: !Sub "table/${ProductsTable}"
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      MinCapacity: 1
      MaxCapacity: 5
      RoleARN: !GetAtt AutoScalingRole.Arn

  ProductsTableWriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: UseProvisionedThroughput
    Properties:
      PolicyName: !Sub "${ProjectName}-${Environment}-products-write-scaling"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ProductsTableWriteScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization

  ProductsTableReadScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: UseProvisionedThroughput
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: !Sub "table/${ProductsTable}"
      ScalableDimension: dynamodb:table:ReadCapacityUnits
      MinCapacity: 1
      MaxCapacity: 5
      RoleARN: !GetAtt AutoScalingRole.Arn

  ProductsTableReadScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: UseProvisionedThroughput
    Properties:
      PolicyName: !Sub "${ProjectName}-${Environment}-products-read-scaling"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ProductsTableReadScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization


  # Carts Table Auto Scaling
  CartsTableWriteScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: UseProvisionedThroughput
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: !Sub "table/${CartsTable}"
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      MinCapacity: 1
      MaxCapacity: 5
      RoleARN: !GetAtt AutoScalingRole.Arn

  CartsTableWriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: UseProvisionedThroughput
    Properties:
      PolicyName: !Sub "${ProjectName}-${Environment}-carts-write-scaling"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref CartsTableWriteScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization

  CartsTableReadScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: UseProvisionedThroughput
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: !Sub "table/${CartsTable}"
      ScalableDimension: dynamodb:table:ReadCapacityUnits
      MinCapacity: 1
      MaxCapacity: 5
      RoleARN: !GetAtt AutoScalingRole.Arn

  CartsTableReadScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: UseProvisionedThroughput
    Properties:
      PolicyName: !Sub "${ProjectName}-${Environment}-carts-read-scaling"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref CartsTableReadScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization


  # Orders Table Auto Scaling
  OrdersTableWriteScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: UseProvisionedThroughput
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: !Sub "table/${OrdersTable}"
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      MinCapacity: 1
      MaxCapacity: 5
      RoleARN: !GetAtt AutoScalingRole.Arn

  OrdersTableWriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: UseProvisionedThroughput
    Properties:
      PolicyName: !Sub "${ProjectName}-${Environment}-orders-write-scaling"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref OrdersTableWriteScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization

  OrdersTableReadScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: UseProvisionedThroughput
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: !Sub "table/${OrdersTable}"
      ScalableDimension: dynamodb:table:ReadCapacityUnits
      MinCapacity: 1
      MaxCapacity: 5
      RoleARN: !GetAtt AutoScalingRole.Arn

  OrdersTableReadScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: UseProvisionedThroughput
    Properties:
      PolicyName: !Sub "${ProjectName}-${Environment}-orders-read-scaling"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref OrdersTableReadScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization


  # Users Table Auto Scaling
  UsersTableWriteScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: UseProvisionedThroughput
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: !Sub "table/${UsersTable}"
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      MinCapacity: 1
      MaxCapacity: 5
      RoleARN: !GetAtt AutoScalingRole.Arn

  UsersTableWriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: UseProvisionedThroughput
    Properties:
      PolicyName: !Sub "${ProjectName}-${Environment}-users-write-scaling"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref UsersTableWriteScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization

  UsersTableReadScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: UseProvisionedThroughput
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: !Sub "table/${UsersTable}"
      ScalableDimension: dynamodb:table:ReadCapacityUnits
      MinCapacity: 1
      MaxCapacity: 5
      RoleARN: !GetAtt AutoScalingRole.Arn

  UsersTableReadScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: UseProvisionedThroughput
    Properties:
      PolicyName: !Sub "${ProjectName}-${Environment}-users-read-scaling"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref UsersTableReadScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization



Outputs:

  ProductsTableName:
    Description: Products DynamoDB table name
    Value: !Ref ProductsTable
    Export:
      Name: !Sub "${ProjectName}-${Environment}-ProductsTableName"

  ProductsTableArn:
    Description: Products DynamoDB table ARN
    Value: !GetAtt ProductsTable.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-ProductsTableArn"

  ProductsTableStreamArn:
    Description: Products DynamoDB table stream ARN
    Value: !GetAtt ProductsTable.StreamArn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-ProductsTableStreamArn"

  CartsTableName:
    Description: Carts DynamoDB table name
    Value: !Ref CartsTable
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CartsTableName"

  CartsTableArn:
    Description: Carts DynamoDB table ARN
    Value: !GetAtt CartsTable.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CartsTableArn"

  OrdersTableName:
    Description: Orders DynamoDB table name
    Value: !Ref OrdersTable
    Export:
      Name: !Sub "${ProjectName}-${Environment}-OrdersTableName"

  OrdersTableArn:
    Description: Orders DynamoDB table ARN
    Value: !GetAtt OrdersTable.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-OrdersTableArn"

  OrdersTableStreamArn:
    Description: Orders DynamoDB table stream ARN
    Value: !GetAtt OrdersTable.StreamArn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-OrdersTableStreamArn"
