AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Edge stack for aws-ecommerce-infrastructure.
  Creates CloudFront distribution, S3 static site bucket,
  and Route 53 DNS records.



Parameters:

  ProjectName:
    Type: String

  Environment:
    Type: String
  
  WebsiteBucketName:
    Type: String

  HostedZoneId:
    Type: String

  DomainName:
    Type: String

  CloudFrontAcmCertificateArn:
    Type: String
  
  EnableWaf:
    Type: String
  


Conditions:

  IsProd: !Equals [!Ref Environment, prod]

  EnableWafCondition: !Equals [!Ref EnableWaf, "true"]



Resources:

  # ----------------------
  # S3 Bucket & Policy
  # ----------------------

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucketName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${WebsiteBucketName}"
              - !Sub "arn:${AWS::Partition}:s3:::${WebsiteBucketName}/*"
            Condition:
              Bool:
                aws:SecureTransport: false
  
  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-${Environment}-cloudfront-logs"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 30
            Prefix: ""
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Disabled
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-cloudfront-logs"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment


  # ----------------------
  # WAF
  # ----------------------

  CloudFrontWebAcl:
    Condition: EnableWafCondition
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-cloudfront-waf"
      Description: !Sub "WAF for ${ProjectName}-${Environment} CloudFront distribution"
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "${ProjectName}-${Environment}-cloudfront-waf"
      Rules:
        - Name: RateLimitPerIP
          Priority: 1
          Statement:
            RateBasedStatement:
              Limit: 1000 # max requests per 5 minutes per IP
              AggregateKeyType: IP
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: rate-limit
          OverrideAction:
            None: {}
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 10
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: common-rules
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 20
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: bad-inputs
        - Name: AWSManagedRulesAmazonIpReputationList
          Priority: 30
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: ip-reputation


  # ----------------------
  # CloudFront Distribution
  # ----------------------

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${ProjectName}-${Environment}-oac"
        Description: !Sub "OAC for ${ProjectName}-${Environment} S3 origin"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  
  CloudFrontResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub "${ProjectName}-${Environment}-security-headers"
        Comment: "Security headers for static website"
        SecurityHeadersConfig:
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 63072000  # 2 years
            IncludeSubdomains: true
            Preload: true
            Override: true
          ContentTypeOptions:
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: strict-origin-when-cross-origin
            Override: true
          XSSProtection:
            Override: true
            Protection: true
            ModeBlock: true
          ContentSecurityPolicy:
            Override: false

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - Fn::If:
            - IsProd
            - !Ref DomainName
            - !Sub "${Environment}.${DomainName}"
        WebACLId:
          Fn::If:
            - EnableWafCondition
            - !Ref CloudFrontWebAcl
            - !Ref AWS::NoValue
        Origins:
          - Id: StaticSiteOrigin
            DomainName: !Sub "${WebsiteBucketName}.s3.amazonaws.com"
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig: {}
          - Id: ApiGatewayOrigin
            DomainName: !ImportValue "${ProjectName}-${Environment}-ApiGatewayDomainName"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              HTTPSPort: 443
              OriginSslProtocols:
                - TLSv1.2
        CacheBehaviors:
          - PathPattern: /api/*
            TargetOriginId: ApiGatewayOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled
            ResponseHeadersPolicyId: !Ref CloudFrontResponseHeadersPolicy
        DefaultCacheBehavior:
          TargetOriginId: StaticSiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
          ResponseHeadersPolicyId: !Ref CloudFrontResponseHeadersPolicy
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /404.html
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudFrontAcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        PriceClass: PriceClass_100
        Comment: !Sub "CloudFront for ${ProjectName}-${Environment} static site"
        Logging:
          Bucket: !Ref LogBucket
          IncludeCookies: false
          Prefix: !Sub "${ProjectName}/${Environment}/"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-cloudfront"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
  

  # ----------------------
  # Route53 DNS Record
  # ----------------------

  WebsiteRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name:
        Fn::If:
          - IsProd
          - !Ref DomainName
          - !Sub "${Environment}.${DomainName}"
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: "Z2FDTNDATAQYW2"  # CloudFront global hosted zone ID
        EvaluateTargetHealth: false



Outputs:

  CloudFrontDistributionId:
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CloudFrontDistributionId"

  CloudFrontDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${ProjectName}-${Environment}-CloudFrontDomainName"