AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Network stack for aws-ecommerce-infrastructure
  Creates VPC, subnets, IGW, route tables for main (AZ1) and pilot light (AZ2)


Parameters:
  ProjectName:
    Type: String
    Description: Project name prefix for resource naming
    Default: candy-store  # Delete Default

  AvailabilityZoneA:
    Type: String
    Description: Availability Zone of main resources
    Default: a  # Delete Default

  AvailabilityZoneB:
    Type: String
    Description: Availability Zone of backup resources (pilot light / failover AZ)
    Default: b  # Delete Default

  Environment:
    Type: String
    Description: Deployment environment
    Default: dev  # Delete Default

  VpcCidr:
    Type: String
    Description: The CIDR block for the VPC
    Default: "10.0.0.0/16"  # Delete Default


Resources:

  # ----------------------
  # VPC & Gateway
  # ----------------------

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-vpc"
  
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-igw"
  
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway


  # ----------------------
  # Subnets
  # ----------------------

  PublicSubnet1a:  
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Select [0, !Cidr [!Ref VpcCidr, 5, 8]]
      AvailabilityZone: !Sub "${AWS::Region}${AvailabilityZoneA}"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-nat-public-subnet-1a"
    # Public Subnet for NAT Gateway
  
  PrivateSubnet2a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Select [1, !Cidr [!Ref VpcCidr, 5, 8]]
      AvailabilityZone: !Sub "${AWS::Region}${AvailabilityZoneA}"
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-ecs-private-subnet-2a"
    # Private Subnet for ECS

  PrivateSubnet3a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Select [2, !Cidr [!Ref VpcCidr, 5, 8]]
      AvailabilityZone: !Sub "${AWS::Region}${AvailabilityZoneA}"
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-aurora-private-subnet-3a"
    # Private Subnet for Aurora

  PublicSubnet2b:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Select [3, !Cidr [!Ref VpcCidr, 5, 8]]
      AvailabilityZone: !Sub "${AWS::Region}${AvailabilityZoneB}"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-ecs-public-subnet-2b"
    # Public Subnet for ECS (backup)

  PrivateSubnet3b:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Select [4, !Cidr [!Ref VpcCidr, 5, 8]]
      AvailabilityZone: !Sub "${AWS::Region}${AvailabilityZoneB}"
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-aurora-private-subnet-3b"
    # Private Subnet for Aurora (backup)


  # ----------------------
  # Route Tables
  # ----------------------

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-public-rt"
    # Route Table for all public subnets
  
  InternetRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
    # Internet Route for Public Route Table
  
  PublicSubnet1aAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1a
      RouteTableId: !Ref PublicRouteTable
    # Associates Public Subnet 1a (NAT Gateway)
  
  PublicSubnet2aAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2b
      RouteTableId: !Ref PublicRouteTable
    # Associates Public Subnet 2b (ECS backup)


Outputs:

  VpcId:
    Description: VPC ID
    Value: !Ref VPC
  
  PublicSubnet1a:
    Description: Public subnet for NAT Gateway in AvailabilityZone-A (main)
    Value: !Ref PublicSubnet1a
  
  PrivateSubnet2a:
    Description: Private subnet for ECS in AvailabilityZone-A (main)
    Value: !Ref PrivateSubnet2a
  
  PrivateSubnet3a:
    Description: Private subnet for Aurora in AvailabilityZone-A (main)
    Value: !Ref PrivateSubnet2a
  
  PublicSubnet2b:
    Description: Public subnet for ECS in AvailabilityZone-B (backup)
    Value: !Ref PublicSubnet2b
  
  PrivateSubnet3b:
    Description: Private subnet for Aurora in AvailabilityZone-B (backup)
    Value: !Ref PrivateSubnet3b