AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Observability stack for aws-ecommerce-infrastructure.
  Creates CloudWatch alarms, dashboards, and SNS topics for monitoring
  Lambda, DynamoDB, API Gateway, and CloudFront.



Parameters:

  ProjectName:
    Type: String

  Environment:
    Type: String

  AlarmEmail:
    Type: String

  EnableAlarms:
    Type: String

  EnableDashboards:
    Type: String



Conditions:

  HasAlarmEmail: !Not [!Equals [!Ref AlarmEmail, ""]]
  EnableAlarmsCondition: !Equals [!Ref EnableAlarms, "true"]
  EnableDashboardsCondition: !Equals [!Ref EnableDashboards, "true"]
  CreateTopic: !And
    - !Condition EnableAlarmsCondition
    - !Condition HasAlarmEmail



Resources:

  # ----------------------
  # SNS Topic for Alarms
  # ----------------------

  AlarmTopic:
    Type: AWS::SNS::Topic
    Condition: CreateTopic
    Properties:
      TopicName: !Sub "${ProjectName}-${Environment}-alarms"
      DisplayName: !Sub "${ProjectName} ${Environment} Alarms"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  AlarmTopicSubscription:
    Type: AWS::SNS::Subscription
    Condition: CreateTopic
    Properties:
      Protocol: email
      TopicArn: !Ref AlarmTopic
      Endpoint: !Ref AlarmEmail


  # ----------------------
  # Lambda Function Alarms
  # ----------------------

  ProductsFunctionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableAlarmsCondition
    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-products-errors"
      AlarmDescription: Products Lambda function error rate is high
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !ImportValue
            Fn::Sub: "${ProjectName}-${Environment}-ProductsFunctionName"
      TreatMissingData: notBreaching
      AlarmActions: !If
        - HasAlarmEmail
        - [!Ref AlarmTopic]
        - []

  ProductsFunctionThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableAlarmsCondition
    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-products-throttles"
      AlarmDescription: Products Lambda function is being throttled
      MetricName: Throttles
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !ImportValue
            Fn::Sub: "${ProjectName}-${Environment}-ProductsFunctionName"
      TreatMissingData: notBreaching
      AlarmActions: !If
        - HasAlarmEmail
        - [!Ref AlarmTopic]
        - []

  CartFunctionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableAlarmsCondition
    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-cart-errors"
      AlarmDescription: Cart Lambda function error rate is high
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !ImportValue
            Fn::Sub: "${ProjectName}-${Environment}-CartFunctionName"
      TreatMissingData: notBreaching
      AlarmActions: !If
        - HasAlarmEmail
        - [!Ref AlarmTopic]
        - []

  CheckoutFunctionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableAlarmsCondition
    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-checkout-errors"
      AlarmDescription: Checkout Lambda function error rate is high
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 3
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !ImportValue
            Fn::Sub: "${ProjectName}-${Environment}-CheckoutFunctionName"
      TreatMissingData: notBreaching
      AlarmActions: !If
        - HasAlarmEmail
        - [!Ref AlarmTopic]
        - []

  OrdersFunctionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableAlarmsCondition
    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-orders-errors"
      AlarmDescription: Orders Lambda function error rate is high
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !ImportValue
            Fn::Sub: "${ProjectName}-${Environment}-OrdersFunctionName"
      TreatMissingData: notBreaching
      AlarmActions: !If
        - HasAlarmEmail
        - [!Ref AlarmTopic]
        - []


  # ----------------------
  # DynamoDB Alarms
  # ----------------------

  ProductsTableReadThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableAlarmsCondition
    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-products-read-throttle"
      AlarmDescription: Products table read requests are being throttled
      MetricName: ReadThrottleEvents
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: TableName
          Value: !ImportValue
            Fn::Sub: "${ProjectName}-${Environment}-ProductsTableName"
      TreatMissingData: notBreaching
      AlarmActions: !If
        - HasAlarmEmail
        - [!Ref AlarmTopic]
        - []

  ProductsTableWriteThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableAlarmsCondition
    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-products-write-throttle"
      AlarmDescription: Products table write requests are being throttled
      MetricName: WriteThrottleEvents
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: TableName
          Value: !ImportValue
            Fn::Sub: "${ProjectName}-${Environment}-ProductsTableName"
      TreatMissingData: notBreaching
      AlarmActions: !If
        - HasAlarmEmail
        - [!Ref AlarmTopic]
        - []

  OrdersTableReadThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableAlarmsCondition
    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-orders-read-throttle"
      AlarmDescription: Orders table read requests are being throttled
      MetricName: ReadThrottleEvents
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: TableName
          Value: !ImportValue
            Fn::Sub: "${ProjectName}-${Environment}-OrdersTableName"
      TreatMissingData: notBreaching
      AlarmActions: !If
        - HasAlarmEmail
        - [!Ref AlarmTopic]
        - []


  # ----------------------
  # API Gateway Alarms
  # ----------------------

  Api4xxErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableAlarmsCondition
    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-api-4xx-errors"
      AlarmDescription: API Gateway 4xx error rate is high
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 50
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiId
          Value: !ImportValue
            Fn::Sub: "${ProjectName}-${Environment}-HttpApiId"
      TreatMissingData: notBreaching
      AlarmActions: !If
        - HasAlarmEmail
        - [!Ref AlarmTopic]
        - []

  Api5xxErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableAlarmsCondition
    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-api-5xx-errors"
      AlarmDescription: API Gateway 5xx error rate is high (critical)
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiId
          Value: !ImportValue
            Fn::Sub: "${ProjectName}-${Environment}-HttpApiId"
      TreatMissingData: notBreaching
      AlarmActions: !If
        - HasAlarmEmail
        - [!Ref AlarmTopic]
        - []

  ApiLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableAlarmsCondition
    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-api-high-latency"
      AlarmDescription: API Gateway latency is high
      MetricName: IntegrationLatency
      Namespace: AWS/ApiGateway
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 3000
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiId
          Value: !ImportValue
            Fn::Sub: "${ProjectName}-${Environment}-HttpApiId"
      TreatMissingData: notBreaching
      AlarmActions: !If
        - HasAlarmEmail
        - [!Ref AlarmTopic]
        - []


  # ----------------------
  # CloudWatch Dashboard
  # ----------------------

  ApplicationDashboard:
    Type: AWS::CloudWatch::Dashboard
    Condition: EnableDashboardsCondition
    Properties:
      DashboardName: !Sub "${ProjectName}-${Environment}-overview"
      DashboardBody:
        Fn::Sub:
          - |
            {
              "widgets": [
                {
                  "type": "metric",
                  "properties": {
                    "title": "Lambda Invocations",
                    "region": "${AWS::Region}",
                    "period": 300,
                    "stat": "Sum",
                    "metrics": [
                      ["AWS/Lambda", "Invocations", "FunctionName", "${ProductsFunctionName}", { "label": "Products" }],
                      ["AWS/Lambda", "Invocations", "FunctionName", "${CartFunctionName}", { "label": "Cart" }],
                      ["AWS/Lambda", "Invocations", "FunctionName", "${CheckoutFunctionName}", { "label": "Checkout" }],
                      ["AWS/Lambda", "Invocations", "FunctionName", "${OrdersFunctionName}", { "label": "Orders" }]
                    ]
                  }
                },
                {
                  "type": "metric",
                  "properties": {
                    "title": "Lambda Errors",
                    "region": "${AWS::Region}",
                    "period": 300,
                    "stat": "Sum",
                    "metrics": [
                      ["AWS/Lambda", "Errors", "FunctionName", "${ProductsFunctionName}", { "label": "Products" }],
                      ["AWS/Lambda", "Errors", "FunctionName", "${CartFunctionName}", { "label": "Cart" }],
                      ["AWS/Lambda", "Errors", "FunctionName", "${CheckoutFunctionName}", { "label": "Checkout" }],
                      ["AWS/Lambda", "Errors", "FunctionName", "${OrdersFunctionName}", { "label": "Orders" }]
                    ]
                  }
                },
                {
                  "type": "metric",
                  "properties": {
                    "title": "Lambda Duration (ms)",
                    "region": "${AWS::Region}",
                    "period": 300,
                    "stat": "Average",
                    "metrics": [
                      ["AWS/Lambda", "Duration", "FunctionName", "${ProductsFunctionName}", { "label": "Products" }],
                      ["AWS/Lambda", "Duration", "FunctionName", "${CartFunctionName}", { "label": "Cart" }],
                      ["AWS/Lambda", "Duration", "FunctionName", "${CheckoutFunctionName}", { "label": "Checkout" }],
                      ["AWS/Lambda", "Duration", "FunctionName", "${OrdersFunctionName}", { "label": "Orders" }]
                    ]
                  }
                },
                {
                  "type": "metric",
                  "properties": {
                    "title": "API Gateway Requests & Errors",
                    "region": "${AWS::Region}",
                    "period": 300,
                    "stat": "Sum",
                    "metrics": [
                      ["AWS/ApiGateway", "Count", "ApiId", "${HttpApiId}", { "label": "Requests" }],
                      ["AWS/ApiGateway", "4XXError", "ApiId", "${HttpApiId}", { "label": "4XX Errors" }],
                      ["AWS/ApiGateway", "5XXError", "ApiId", "${HttpApiId}", { "label": "5XX Errors" }]
                    ]
                  }
                },
                {
                  "type": "metric",
                  "properties": {
                    "title": "DynamoDB Capacity Units",
                    "region": "${AWS::Region}",
                    "period": 300,
                    "stat": "Sum",
                    "metrics": [
                      ["AWS/DynamoDB", "ConsumedReadCapacityUnits", "TableName", "${ProductsTableName}", { "label": "Products Read" }],
                      ["AWS/DynamoDB", "ConsumedWriteCapacityUnits", "TableName", "${ProductsTableName}", { "label": "Products Write" }],
                      ["AWS/DynamoDB", "ConsumedReadCapacityUnits", "TableName", "${CartsTableName}", { "label": "Carts Read" }],
                      ["AWS/DynamoDB", "ConsumedWriteCapacityUnits", "TableName", "${CartsTableName}", { "label": "Carts Write" }],
                      ["AWS/DynamoDB", "ConsumedReadCapacityUnits", "TableName", "${OrdersTableName}", { "label": "Orders Read" }],
                      ["AWS/DynamoDB", "ConsumedWriteCapacityUnits", "TableName", "${OrdersTableName}", { "label": "Orders Write" }]
                    ]
                  }
                }
              ]
            }
          - ProductsFunctionName: !ImportValue
              Fn::Sub: "${ProjectName}-${Environment}-ProductsFunctionName"
            CartFunctionName: !ImportValue
              Fn::Sub: "${ProjectName}-${Environment}-CartFunctionName"
            CheckoutFunctionName: !ImportValue
              Fn::Sub: "${ProjectName}-${Environment}-CheckoutFunctionName"
            OrdersFunctionName: !ImportValue
              Fn::Sub: "${ProjectName}-${Environment}-OrdersFunctionName"
            HttpApiId: !ImportValue
              Fn::Sub: "${ProjectName}-${Environment}-HttpApiId"
            ProductsTableName: !ImportValue
              Fn::Sub: "${ProjectName}-${Environment}-ProductsTableName"
            CartsTableName: !ImportValue
              Fn::Sub: "${ProjectName}-${Environment}-CartsTableName"
            OrdersTableName: !ImportValue
              Fn::Sub: "${ProjectName}-${Environment}-OrdersTableName"



Outputs:

  AlarmTopicArn:
    Description: SNS Topic ARN for alarms
    Value: !If
      - CreateTopic
      - !Ref AlarmTopic
      - "No alarm topic configured"
    Export:
      Name: !Sub "${ProjectName}-${Environment}-AlarmTopicArn"

  DashboardUrl:
    Description: CloudWatch Dashboard URL
    Value: !If
      - EnableDashboardsCondition
      - !Sub "https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${ProjectName}-${Environment}-overview"
      - "Dashboard not enabled"