AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Root CloudFormation template for an e-commerce website infrastructure.
  This template orchestrates the deployment of all nested stacks:
  network, endpoints, compute, database, and edge.

Parameters:
  ProjectName:
    Type: String
    Default: candy-store
    Description: Project name prefix for resource naming
  
  Region:
    Type: String
    Default: us-east-1
    Description: AWS region to deploy resources
  
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment environment
  
  NestedTemplateURL:
    Type: String
    Description: >
      URL of root directory where the nested stack templates are stored (network.yaml, endpoints.yaml, compute.yaml, database.yaml, edge.yaml)
      Can be Github (https://raw.githubusercontent.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME/main/cloudformation/) or S3 (https://BUCKET_NAME.s3.amazonaws.com/)
    Default: https://raw.githubusercontent.com/floydmoratti/YOUR_REPO_NAME/dev/cloudformation/

Resources:

  # ----------------------
  # Network Stack
  # ----------------------

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.amazonaws.com/network.yaml