AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Root CloudFormation template for an e-commerce website infrastructure.
  This template orchestrates the deployment of all nested stacks:
  network, endpoints, compute, database, and edge.


Parameters:

  ProjectName:
    Type: String
    Description: Project name prefix for resource naming
    Default: candy-store
  
  DatabaseName:
    Type: String
    Description: >
      Initial database name (lowercase, letters/numbers/underscores only).
      Must start with a letter.
    MinLength: 1
    MaxLength: 55
    AllowedPattern: "^[a-z][a-z0-9_]*$"
    ConstraintDescription: >
      Database name must start with a lowercase letter and contain only
      lowercase letters, numbers, and underscores.
    Default: candy_store

  ContainerName:
    Type: String
    Description: Container name
    Default: candy-store-api

  ContainerVersion:
    Type: String
    Description: Container image tag to deploy (e.g. latest, v1.0.0)
    Default: latest  # Delete Default

  EcrRepositoryUri:
    Type: String
    Description: URI of ECR Repository

  WebsiteBucketName:
    Type: String
    Description: Name of S3 bucket hosting static website
  
  VpcCidr:
    Type: String
    Description: The CIDR block for the VPC
    Default: "10.0.0.0/16"
    AllowedPattern: "^([0-9]{1,3}\\.){3}[0-9]{1,3}/[0-9]{1,2}$"
    ConstraintDescription: "Must be a valid CIDR block, e.g., 10.0.0.0/16"
  
  Environment:
    Type: String
    Description: Deployment environment
    Default: dev
    AllowedValues:
      - dev
      - prod
  
  TemplatesBaseUrl:
    Type: String
    Description: >
      URL of root directory where the nested stack templates are stored (network.yaml, endpoints.yaml, compute.yaml, database.yaml, edge.yaml)
      Can be Github (https://raw.githubusercontent.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME/main/cloudformation) or S3 (https://BUCKET_NAME.s3.amazonaws.com)
      Note: Do not include trailing slash "/"
    Default: https://raw.githubusercontent.com/floydmoratti/aws-ecommerce-infrastructure/dev/cloudformation

  AuroraEngineVersion:
    Type: String
    Description: Aurora PostgreSQL major version
    Default: "15.4"  # Delete Default

  DesiredCount:
    Type: Number
    Description: Desired count for main ECS service.
    Default: 0

  BackupDesiredCount:
    Type: Number
    Description: Desired count for pilot light ECS service. Can be updated by Step Functions or manually.
    Default: 0
  
  EcsLogRetention:
    Type: Number
    Description: How many days to keep logs from ECS tasks
    Default: 30

  DomainName:
    Type: String
    Description: Root domain for the website (e.g. example.com)
    Default: floydmoratti.website  # Delete Default

  HostedZoneId:
    Type: String
    Description: Route 53 Hosted Zone ID for website domain
  
  CloudFrontAcmCertificateArn:
    Type: String
    Description: >
      ARN of ACM certificate for CloudFront HTTPS (WARNING must be generated in region us-east-1).
  
  EnableWaf:
    Type: String
    AllowedValues:
      - true
      - false
    Description: Whether to enable AWS WAF for CloudFront
    Default: false  # Delete Default


Resources:

  # ----------------------
  # Nested Stacks
  # ----------------------

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplatesBaseUrl}/network.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        VpcCidr: !Ref VpcCidr
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-network-stack"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    # Nested stack for network resources: VPC, subnets, routes, and Internet Gateway.
    # Resources are deleted on stack removal to avoid ongoing demo costs
  

  EndpointsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplatesBaseUrl}/endpoints.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicAlbSubnet1a: !GetAtt NetworkStack.Outputs.PublicAlbSubnet1a
        PrivateEcsSubnet2a: !GetAtt NetworkStack.Outputs.PrivateEcsSubnet2a
        PrivateDbSubnet3a: !GetAtt NetworkStack.Outputs.PrivateDbSubnet3a
        PublicEcsSubnet2b: !GetAtt NetworkStack.Outputs.PublicEcsSubnet2b
        PrivateDbSubnet3b: !GetAtt NetworkStack.Outputs.PrivateDbSubnet3b
        InternetGatewayId: !GetAtt NetworkStack.Outputs.InternetGatewayId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-endpoints-stack"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    # Nested stack for endpoints: NAT Gateway, S3 Gateway and Private Routes.
    # Depends on the NetworkStack because it needs VPC and subnet information


  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplatesBaseUrl}/database.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        DatabaseName: !Ref DatabaseName
        Environment: !Ref Environment
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PrivateDbSubnet3a: !GetAtt NetworkStack.Outputs.PrivateDbSubnet3a
        PrivateDbSubnet3b: !GetAtt NetworkStack.Outputs.PrivateDbSubnet3b
        AuroraEngineVersion: !Ref AuroraEngineVersion
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-database-stack"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    # Nested stack for the Aurora Serverless database
    # Depends on the NetworkStack because it requires private subnets


  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplatesBaseUrl}/compute.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicAlbSubnet1a: !GetAtt NetworkStack.Outputs.PublicAlbSubnet1a
        PrivateEcsSubnet2a: !GetAtt NetworkStack.Outputs.PrivateEcsSubnet2a
        PublicAlbSubnet1b: !GetAtt NetworkStack.Outputs.PublicAlbSubnet1b
        PublicEcsSubnet2b: !GetAtt NetworkStack.Outputs.PublicEcsSubnet2b
        DatabaseSecretArn: !GetAtt DatabaseStack.Outputs.DatabaseSecretArn
        DbSecurityGroup: !GetAtt DatabaseStack.Outputs.DbSecurityGroup
        DesiredCount: !Ref DesiredCount
        BackupDesiredCount: !Ref BackupDesiredCount
        EcsLogRetention: !Ref EcsLogRetention
        ContainerName: !Ref ContainerName
        ContainerVersion: !Ref ContainerVersion
        EcrRepositoryUri: !Ref EcrRepositoryUri
        AuroraDatabaseName: !GetAtt DatabaseStack.Outputs.AuroraDatabaseName
        AuroraWriterEndpoint: !GetAtt DatabaseStack.Outputs.AuroraWriterEndpoint
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-compute-stack"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    # Nested stack for ECS compute resources, ALB, IAM roles, and Secrets Manager
    # Depends on NetworkStack, DatabaseStack


  EdgeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplatesBaseUrl}/edge.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        AlbDnsName: !GetAtt ComputeStack.Outputs.AlbDnsName
        WebsiteBucketName: !Ref WebsiteBucketName
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId
        AlbHostedZoneId: !GetAtt ComputeStack.Outputs.AlbHostedZoneId
        CloudFrontAcmCertificateArn: !Ref CloudFrontAcmCertificateArn
        EnableWaf: !Ref EnableWaf
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-edge-stack"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    # Nested stack for CloudFront and S3 static content distribution
    # Depends on ComputeStack because it uses the ALB and S3 bucket outputs


Outputs:

  VpcId:
    Description: Id of VPC
    Value: !GetAtt NetworkStack.Outputs.VpcId

  NetworkStackId:
    Description: Stack ID of the network resources
    Value: !Ref NetworkStack
  
  ComputeStackId:
    Description: Stack ID of the compute resources
    Value: !Ref ComputeStack

  DatabaseStackId:
    Description: Stack ID of the database resources
    Value: !Ref DatabaseStack

  EdgeStackId:
    Description: Stack ID of the edge resources
    Value: !Ref EdgeStack

  DomainName:
    Description: Root domain for the website (e.g. example.com)
    Value: !Ref DomainName

  HostedZoneId:
    Description: Route 53 Hosted Zone ID for website domain
    Value: !Ref HostedZoneId