AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Database stack for aws-ecommerce-infrastructure.
  Creates Aurora Serverless cluster with writer in AZ1 and reader in AZ2, plus Secrets Manager.


Parameters:

  ProjectName:
    Type: String
    Description: Project name prefix for resource naming
    Default: candy-store  # Delete Default

  DatabaseName:
    Type: String
    Description: Initial database name (lowercase, letters/numbers/underscores only)
    Default: candy_store  # Delete Default
  
  Environment:
    Type: String
    Description: Deployment environment
    Default: dev  # Delete Default
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID from network stack
  
  PrivateDbSubnet3a:
    Type: AWS::EC2::Subnet::Id
    Description: Private subnet for Aurora in AvailabilityZone-A (main)

  PrivateDbSubnet3b:
    Type: AWS::EC2::Subnet::Id
    Description: Private subnet for Aurora in AvailabilityZone-B (backup)

  AuroraEngineVersion:
    Type: String
    Description: Aurora PostgreSQL major version
    Default: "15.4"  # Delete Default


Resources:

  # ----------------------
  # Security Group
  # ----------------------

  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to Aurora Serverless v2 cluster from ECS subnets only
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-aurora-sg"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
      # Ingress rule added in ComputeStack to allow ECS access


  # ----------------------
  # Secrets Manager
  # ----------------------

  DatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-db-credentials"
      Description: "Database credentials for Aurora cluster"
      KmsKeyId: alias/aws/secretsmanager  # default AWS key
      GenerateSecretString:
        SecretStringTemplate: '{"username":"dbadmin"}'
        GenerateStringKey: "password"
        ExcludeCharacters: '"@/\'
        PasswordLength: 16
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-db-credentials"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete


  # ----------------------
  # Aurora Serverless Cluster
  # ----------------------

  AuroraSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub "Aurora private subnets for ${ProjectName}-${Environment}"
      SubnetIds:
        - !Ref PrivateDbSubnet3a
        - !Ref PrivateDbSubnet3b
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-aurora-subnet-group"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
  
  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineVersion: !Ref AuroraEngineVersion
      DatabaseName: !Sub "${DatabaseName}_${Environment}_db"
      MasterUsername: !Sub "{{resolve:secretsmanager:${DatabaseSecret}:SecretString:username}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${DatabaseSecret}:SecretString:password}}"
      DBSubnetGroupName: !Ref AuroraSubnetGroup
      VpcSecurityGroupIds:
        - !Ref DbSecurityGroup
      AvailabilityZones:
        - !Select [0, !GetAZs ""]
        - !Select [1, !GetAZs ""]
      BackupRetentionPeriod: 7
      PreferredBackupWindow: "07:00-07:30"
      PreferredMaintenanceWindow: "Sun:05:00-Sun:05:30"
      ServerlessV2ScalingConfiguration:
        MinCapacity: 0.5
        MaxCapacity: 1
      # DeletionProtection: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-aurora-cluster"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
  
  AuroraWriterInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${ProjectName}-${Environment}-aurora-writer"
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: db.serverless
      Engine: aurora-postgresql
      AvailabilityZone: !Select [0, !GetAZs ""]
      PubliclyAccessible: false
      AutoMinorVersionUpgrade: true
      PromotionTier: 0
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-aurora-writer"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
  
  AuroraReaderInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${ProjectName}-${Environment}-aurora-reader"
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: db.serverless
      Engine: aurora-postgresql
      AvailabilityZone: !Select [1, !GetAZs ""]
      PubliclyAccessible: false
      AutoMinorVersionUpgrade: true
      PromotionTier: 1
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-aurora-reader"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete


Outputs:

  AuroraDatabaseName:
    Description: Aurora database name
    Value: !Sub "${DatabaseName}_${Environment}_db"

  AuroraClusterId:
    Description: Aurora cluster Id
    Value: !Ref AuroraCluster

  AuroraWriterEndpoint:
    Description: Aurora cluster writer endpoint
    Value: !GetAtt AuroraCluster.Endpoint.Address
  
  AuroraReaderEndpoint:
    Description: Aurora cluster reader endpoint
    Value: !GetAtt AuroraCluster.ReadEndpoint.Address
  
  DatabaseSecretArn:
    Description: Secrets Manager ARN for database credentials
    Value: !Ref DatabaseSecret
  
  DbSecurityGroup:
    Description: Database Security Group
    Value: !Ref DbSecurityGroup