AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Edge stack for aws-ecommerce-infrastructure.
  Creates CloudFront distribution in front of S3 bucket static website with HTTPS and optional WAF.


Parameters:

  ProjectName:
    Type: String
    Description: Project name prefix for resource naming
    Default: candy-store  # Delete Default
  
  Environment:
    Type: String
    Description: Deployment environment
    Default: dev  # Delete Default
  
  WebsiteBucketName:
    Type: String
    Description: Name of S3 bucket hosting static website
  
  AlbDnsName:
    Type: String
    Description: DNS name of the Application Load Balancer (from compute stack)
  
  DomainName:
    Type: String
    Description: Root domain for the website (e.g. example.com)
    Default: floydmoratti.website  # Delete Default

  HostedZoneId:
    Type: String
    Description: Route 53 Hosted Zone ID for website domain
  
  AlbHostedZoneId:
    Type: String
    Description: Hosted Zone ID of the Application Load Balancer (from compute stack)
  
  CloudFrontAcmCertificateArn:
    Type: String
    Description: >
      ARN of ACM certificate for CloudFront HTTPS (WARNING must be generated in region us-east-1).
      Seperate template called "cert.yaml" provided with "cert-params.yaml"
  
  EnableWaf:
    Type: String
    AllowedValues:
      - true
      - false
    Description: Whether to enable AWS WAF for CloudFront
    Default: false  # Delete Default


Conditions:
  IsProd: !Equals [!Ref Environment, prod]

  EnableWafCondition: !Equals [!Ref EnableWaf, "true"]



Resources:

  # ----------------------
  # Route53 Records
  # ----------------------
  
  ApiRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name:
        Fn::If:
          - IsProd
          - !Sub "api.${DomainName}"
          - !Sub "api.${Environment}.${DomainName}"
      Type: A
      AliasTarget:
        DNSName: !Ref AlbDnsName
        HostedZoneId: !Ref AlbHostedZoneId
        EvaluateTargetHealth: false
  
  WebsiteRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name:
        Fn::If:
          - IsProd
          - !Ref DomainName
          - !Sub "${Environment}.${DomainName}"
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: "Z2FDTNDATAQYW2"  # CloudFront global hosted zone ID
        EvaluateTargetHealth: false  


  # ----------------------
  # WAF
  # ----------------------

  CloudFrontWebAcl:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-cloudfront-waf"
      Description: !Sub "WAF for ${ProjectName}-${Environment} CloudFront distribution"
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "${ProjectName}-${Environment}-cloudfront-waf"
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 10
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: common-rules
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 20
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: bad-inputs
        - Name: AWSManagedRulesAmazonIpReputationList
          Priority: 30
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: ip-reputation


  # ----------------------
  # CloudFront Distribution
  # ----------------------

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${ProjectName}-${Environment}-s3-oac"
        Description: !Sub "OAC for ${ProjectName}-${Environment} S3 origin"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  
  CloudFrontResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub "${ProjectName}-${Environment}-security-headers"
        Comment: "Security headers for static website"
        SecurityHeadersConfig:
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 63072000  # 2 years
            IncludeSubdomains: true
            Preload: true
            Override: true
          ContentTypeOptions:
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: strict-origin-when-cross-origin
            Override: true

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - Fn::If:
            - IsProd
            - !Ref DomainName
            - !Sub "${Environment}.${DomainName}"
        WebACLId:
          Fn::If:
            - EnableWafCondition
            - !Ref CloudFrontWebAcl
            - !Ref AWS::NoValue
        Origins:
          - Id: S3Origin
            DomainName: !Sub "${WebsiteBucketName}.s3.amazonaws.com"
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ResponseHeadersPolicyId: !Ref CloudFrontResponseHeadersPolicy
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /404.html
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudFrontAcmCertificateArn
          SslSupportMethod: sni-only
        PriceClass: PriceClass_100
        Comment: !Sub "CloudFront for ${ProjectName}-${Environment} static site"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-cloudfront"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
    

  # ----------------------
  # S3 Bucket Policy
  # ----------------------

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucketName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontReadOnly
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "arn:${AWS::Partition}:s3:::${WebsiteBucketName}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${WebsiteBucketName}"
              - !Sub "arn:${AWS::Partition}:s3:::${WebsiteBucketName}/*"
            Condition:
              Bool:
                aws:SecureTransport: false
    # S3 Bucket needs public access blocked and not set to static website hosting


Outputs:

  CloudFrontDomain:
    Description: CloudFront domain name for static website
    Value: !GetAtt CloudFrontDistribution.DomainName
  
  CloudFrontWebAclArn:
    Condition: EnableWafCondition
    Description: WAF Web ACL ARN
    Value: !GetAtt CloudFrontWebAcl.Arn

  ApiSubdomain:
    Description: API subdomain pointing to ALB
    Value:
      Fn::If:
        - IsProd
        - !Sub "api.${DomainName}"
        - !Sub "api.${Environment}.${DomainName}"