AWSTemplateFormatVersion: "2010-09-09"
Description: >
  API stack for aws-ecommerce-infrastructure.
  Creates HTTP API Gateway with Lambda integration for /api/* routes.



Parameters:

  ProjectName:
    Type: String

  Environment:
    Type: String

  LambdaS3Bucket:
    Type: String

  ProductsLambdaS3Key:
    Type: String

  CartLambdaS3Key:
    Type: String

  CheckoutLambdaS3Key:
    Type: String

  OrdersLambdaS3Key:
    Type: String



Resources:

  # ----------------------
  # IAM Roles
  # ----------------------

  LambdaIngestRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${Environment}-products-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole  # Cloudwatch logging
      Policies:
        - PolicyName: !Sub "${ProjectName}-${Environment}-products-lambda-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: DynamoDBAccess
                Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/fx/api/access_key"
              - Sid: S3WriteRawFXData
                Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - !Sub "${FxDataBucket.Arn}/raw/*"
              - Sid: CloudWatchLogging
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - "*"
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project